import turtle


    
turtle.color("green")
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.color("green")
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
t.color("green")
t.shape ("turtle")
t.shapesize(50, 50, 50)
t.speed(10)
t.bgcolor("black")
t.pensize(5)
t.pencolor("yellow")

t.pencolor("red")
t.circle(100)
t.color("red")
t.penup()
t.pencolor("blue")
t.circle(10)
t.pencolor("red")
t.pencolor("white")
t.color("blue")
t.penup()
t.circle(10)
t.pencolor("red")
t.color("red")
t.penup()
t.circle(10)
t.pencolor("red")
t.pencolor("blue")
t.color("blue")
t.penup()
t.circle(10)
t.pencolor("red")
t.pencolor("cyan")
t.color("red")
t.penup()
t.pencolor("blue")
t.circle(10)
t.pencolor("red")
t.pencolor("magenta")
t.color("blue")
t.penup()
t.circle(10)
t.pencolor("red")
t.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
t.color("green")
t.shape ("turtle")
t.shapesize(50, 50, 50)
t.speed(10)
t.bgcolor("black")
t.pensize(5)
t.pencolor("yellow")

t.pencolor("red")
t.circle(100)
t.color("red")
t.penup()
t.pencolor("blue")
t.circle(10)
t.pencolor("red")
t.pencolor("white")
t.color("blue")
t.penup()
t.circle(10)
t.pencolor("red")
t.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
t.color("green")
t.shape ("turtle")
t.shapesize(50, 50, 50)
t.speed(10)
t.bgcolor("black")
t.pensize(5)
t.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.color("green")
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.color("green")
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.color("green")
turtle.shape ("turtle")
turtle.shapesize(50, 50, 50)
turtle.speed(10)
turtle.bgcolor("black")
turtle.pensize(5)
turtle.pencolor("yellow")

turtle.pencolor("red")
turtle.circle(100)
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("white")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.color("red")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("blue")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("cyan")
turtle.color("red")
turtle.penup()
turtle.pencolor("blue")
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("magenta")
turtle.color("blue")
turtle.penup()
turtle.circle(10)
turtle.pencolor("red")
turtle.pencolor("orange")
turtle.color("red")
turtle.pencolor("blue")
t = turtle.Turtle()
turtle.done()


